### ISSUE TITLE
Server-less Jenkins using Jenkinsfile runner

### ISSUE THREAD

**Issue by hrishin** [fabric8io/fabric8-build-team#58]
POC using Jenkinsfile Runner to enable serverless Jenkins for build service. 

- [ ] Jenkinsfile runner build - using custom Jenkins war package
   - Use a current set of plugins from plugin.txt and plugins (e.g. syn plugin, bayesian) directory
   - Jenkins configuration 
       - script approval configurations
       - kubernetes slave configuration

- [ ] Run OSIO pipeline 
- [ ] Pipeline progress
  - Store and stream build logs 
  - Sync build stages (build image, rollout to run)
- [ ] Packaging and OpenShift integration
  - Onboarding and launching a project
  - Execute Jenkinsfile Runner builds using OpenShift BuildConfig/Deployment/Job
- [ ] Investigate
  - How to promote builds manually
  - How to run the scheduled build
  - CI/CD integration and handle GitHub webhooks

**Comment by chmouel** [comment]
The  start of my POC is here: 

https://github.com/chmouel/openshift-jr

it's a bit of a dump of my experimentation and not cleanup  but it's able to run osio-pipeline from jenkinsfile-runner,
